// <auto-generated />
using System;
using HolidayDal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HolidayDal.Migrations
{
    [DbContext(typeof(manojdbcontext))]
    [Migration("20231114140344_a1")]
    partial class a1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HolidayDal.designation", b =>
                {
                    b.Property<int>("designationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("designationId"), 1L, 1);

                    b.Property<string>("desigantionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("salary")
                        .HasColumnType("float");

                    b.HasKey("designationId");

                    b.ToTable("designation");
                });

            modelBuilder.Entity("HolidayDal.employee", b =>
                {
                    b.Property<int>("empId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("empId"), 1L, 1);

                    b.Property<DateTime>("DOJ")
                        .HasColumnType("datetime2");

                    b.Property<string>("empName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("isactive")
                        .HasColumnType("bit");

                    b.Property<int>("roledesignationId")
                        .HasColumnType("int");

                    b.HasKey("empId");

                    b.HasIndex("roledesignationId");

                    b.ToTable("employee");
                });

            modelBuilder.Entity("HolidayDal.employee", b =>
                {
                    b.HasOne("HolidayDal.designation", "role")
                        .WithMany("emp")
                        .HasForeignKey("roledesignationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("HolidayDal.designation", b =>
                {
                    b.Navigation("emp");
                });
#pragma warning restore 612, 618
        }
    }
}
