// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using labdal;

#nullable disable

namespace labdal.Migrations
{
    [DbContext(typeof(snehadbcontext))]
    partial class snehadbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("coursestudent", b =>
                {
                    b.Property<int>("coursescourseid")
                        .HasColumnType("int");

                    b.Property<int>("manystudentsId")
                        .HasColumnType("int");

                    b.HasKey("coursescourseid", "manystudentsId");

                    b.HasIndex("manystudentsId");

                    b.ToTable("coursestudent");
                });

            modelBuilder.Entity("labdal.company", b =>
                {
                    b.Property<int>("companyid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("companyid"), 1L, 1);

                    b.Property<string>("companyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("joinedcmpnyyId")
                        .HasColumnType("int");

                    b.HasKey("companyid");

                    b.HasIndex("joinedcmpnyyId");

                    b.ToTable("companies");
                });

            modelBuilder.Entity("labdal.course", b =>
                {
                    b.Property<int>("courseid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("courseid"), 1L, 1);

                    b.Property<string>("courseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("courseid");

                    b.ToTable("course");
                });

            modelBuilder.Entity("labdal.student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("stuName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("student");
                });

            modelBuilder.Entity("coursestudent", b =>
                {
                    b.HasOne("labdal.course", null)
                        .WithMany()
                        .HasForeignKey("coursescourseid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("labdal.student", null)
                        .WithMany()
                        .HasForeignKey("manystudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("labdal.company", b =>
                {
                    b.HasOne("labdal.student", "joinedcmpnyy")
                        .WithMany()
                        .HasForeignKey("joinedcmpnyyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("joinedcmpnyy");
                });
#pragma warning restore 612, 618
        }
    }
}
